# Generated by Django 3.0.3 on 2020-02-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_modifier', '0003_image_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='TheImage',
        ),
    ]
